version: "3.8"
   
services:
  redis:
    container_name: RedisChannel
    restart: always
    image: redis:5
    expose: 
      - "6379"
      
#  db:
#    container_name: PostgresDB 
#    image: postgres:latest
#    restart: always
#    environment:
#      - POSTGRES_DB=-
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgresdjango
  db:
    container_name: PostgresDB 
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "192.168.43.113:5432:5432"
  mainapp:
    restart: always
    build: .
    container_name: ChatApp
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "192.168.43.113:8000:8000"
    links: 
      - redis
      - db
    depends_on:
      - db
