# Generated by Django 3.1.3 on 2020-11-23 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
                ('time_sent', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.IntegerField()),
                ('friend_request', models.CharField(default='NOT SENT', max_length=15)),
                ('friend_status', models.BooleanField(default=False)),
                ('from_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userone', to=settings.AUTH_USER_MODEL)),
                ('to_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertwo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
