# Generated by Django 3.1.3 on 2020-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='relation_name',
            field=models.IntegerField(unique=True),
        ),
    ]
